name: Contrib metadata check

inputs:
  github_token:
    required: true
  mode:
    description: "Behavior mode: 'warn' (default) or 'fail'. 'warn' posts a comment but doesn't fail the CI, while 'fail' posts a comment and fails the CI if contributors are missing."
    required: false
    default: warn


runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install deps
      run: python -m pip install pyyaml requests
      shell: bash

    - name: Run check script
      run: python "$GITHUB_ACTION_PATH/.github/scripts/check_contributors.py"
      shell: bash