name: Contributors metadata check
description: Checks if code contributors are properly listed in metadata files (CITATION.cff / codemeta.json) based on the git history

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  github_token:
    required: true
  mode:
    description: "Behavior mode: 'warn' (default) or 'fail'. 'warn' posts a comment but doesn't fail the CI, while 'fail' posts a comment and fails the CI if contributors are missing."
    required: false
    default: warn
  ignore_emails:
    description: "Comma-separated list of email addresses to ignore when checking contributors (e.g., 'bot@example.com,ci@example.com')"
    required: false
    default: ""
  ignore_logins:
    description: "Comma-separated list of login names to ignore when checking contributors (e.g., 'dependabot[bot],ci-bot')"
    required: false
    default: ""


runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install contrib-checker package
      run: python -m pip install ${{ github.action_path }}
      shell: bash

    - name: Run contributor check
      run: python -m contrib_checker.github
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
        PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        ACTION_MODE: ${{ inputs.mode }}
        ACTION_IGNORE_EMAILS: ${{ inputs.ignore_emails }}
        ACTION_IGNORE_LOGINS: ${{ inputs.ignore_logins }}
